CREATE TABLE IF NOT EXISTS "varit_study_card_item" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "varit_study_card_item_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cardId" integer NOT NULL,
	"nameTitle" text NOT NULL,
	"description" text,
	"linkUrl" varchar(2048),
	"value" integer DEFAULT 0 NOT NULL,
	"itemDate" date,
	"media" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "varit_study_card_item" ADD COLUMN IF NOT EXISTS "description" text;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'varit_study_card_item_cardId_varit_study_card_id_fk'
  ) THEN
    ALTER TABLE "varit_study_card_item"
      ADD CONSTRAINT "varit_study_card_item_cardId_varit_study_card_id_fk"
      FOREIGN KEY ("cardId") REFERENCES "public"."varit_study_card"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_card_item_card_idx" ON "varit_study_card_item" USING btree ("cardId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_card_item_date_idx" ON "varit_study_card_item" USING btree ("itemDate");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_card_item_created_idx" ON "varit_study_card_item" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_card_cursor_idx" ON "varit_study_card" USING btree ("createdAt","id");