CREATE TABLE IF NOT EXISTS "varit_user" (
	"id" varchar(255) PRIMARY KEY NOT NULL,
	"name" varchar(255),
	"email" varchar(320) NOT NULL,
	"emailVerified" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
	"image" varchar(2048)
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "varit_account" (
	"userId" varchar(255) NOT NULL,
	"type" varchar(255) NOT NULL,
	"provider" varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	"refresh_token" text,
	"access_token" text,
	"expires_at" integer,
	"token_type" varchar(255),
	"scope" varchar(255),
	"id_token" text,
	"session_state" varchar(255),
	CONSTRAINT "varit_account_provider_providerAccountId_pk" PRIMARY KEY("provider","providerAccountId")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "varit_project_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "varit_project_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"allowAnonCreate" boolean DEFAULT false NOT NULL,
	"defaultCardVisibility" varchar(20) DEFAULT 'private' NOT NULL,
	"allowedEmails" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "varit_session" (
	"sessionToken" varchar(255) PRIMARY KEY NOT NULL,
	"userId" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "varit_study_card_share" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "varit_study_card_share_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"cardId" integer NOT NULL,
	"email" varchar(320) NOT NULL,
	"permission" varchar(10) DEFAULT 'view' NOT NULL,
	"invitedAt" timestamp with time zone NOT NULL,
	"acceptedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "varit_verification_token" (
	"identifier" varchar(255) NOT NULL,
	"token" varchar(255) NOT NULL,
	"expires" timestamp with time zone NOT NULL,
	CONSTRAINT "varit_verification_token_identifier_token_pk" PRIMARY KEY("identifier","token")
);
--> statement-breakpoint
ALTER TABLE "varit_study_card" ADD COLUMN IF NOT EXISTS "ownerUserId" varchar(255);--> statement-breakpoint
ALTER TABLE "varit_study_card" ADD COLUMN IF NOT EXISTS "visibility" varchar(20) DEFAULT 'private' NOT NULL;--> statement-breakpoint
ALTER TABLE "varit_study_card" ADD COLUMN IF NOT EXISTS "shareToken" varchar(48);--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'varit_account_userId_varit_user_id_fk'
  ) THEN
    ALTER TABLE "varit_account" ADD CONSTRAINT "varit_account_userId_varit_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."varit_user"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'varit_session_userId_varit_user_id_fk'
  ) THEN
    ALTER TABLE "varit_session" ADD CONSTRAINT "varit_session_userId_varit_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."varit_user"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'varit_study_card_share_cardId_varit_study_card_id_fk'
  ) THEN
    ALTER TABLE "varit_study_card_share" ADD CONSTRAINT "varit_study_card_share_cardId_varit_study_card_id_fk" FOREIGN KEY ("cardId") REFERENCES "public"."varit_study_card"("id") ON DELETE cascade ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "account_user_id_idx" ON "varit_account" USING btree ("userId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "session_user_id_idx" ON "varit_session" USING btree ("userId");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "study_card_share_card_email_uq" ON "varit_study_card_share" USING btree ("cardId","email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_card_share_email_idx" ON "varit_study_card_share" USING btree ("email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_card_share_card_idx" ON "varit_study_card_share" USING btree ("cardId");--> statement-breakpoint
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'varit_study_card_ownerUserId_varit_user_id_fk'
  ) THEN
    ALTER TABLE "varit_study_card" ADD CONSTRAINT "varit_study_card_ownerUserId_varit_user_id_fk" FOREIGN KEY ("ownerUserId") REFERENCES "public"."varit_user"("id") ON DELETE set null ON UPDATE no action;
  END IF;
END $$;--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_card_owner_idx" ON "varit_study_card" USING btree ("ownerUserId");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "study_card_visibility_idx" ON "varit_study_card" USING btree ("visibility");--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "study_card_share_token_uq" ON "varit_study_card" USING btree ("shareToken");